import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/toaster";
import Link from "next/link";
import {Button} from "@/components/ui/button";
import {House} from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-100 p-4">
        <nav>
          <Link href="/">
            <Button variant="link" className="hover:text-blue-500">
              <House className="w-8 h-8"/>
              Home
            </Button>
          </Link>
        </nav>
      </header>
      <main>
        {children}
      </main>
    </div>
    <Toaster/>
    </body>
    </html>
  );
}
